const jCategory = [
  {
    index: 0,
    image: "../images/google.png",
    title: "Web Developer",
    rate: "$900 -1200/m",
    avai: "Full Time",
    companyname:"Google",
    location:"USA",
    vacancy:"01",
    hours: "50h / Week",
    description: "We are looking for an outstanding Web Developer to be responsible for the coding, innovative design and layout of our website. Web developer responsibilities include building our website from concept all the way to completion from the bottom up, fashioning everything from the home page to site layout and function.",
    workplace:"Work From home",
    education:"UG: Any Graduate",
    experience: "0 to 2 years",

  },
  {
    index: 1,
    image: "../images/uber.png",
    title: "Web Developer",
    rate: "$900 -1200/m",
    avai: "Full Time",
  },
  {
    index: 2,
    image: "../images/yahoo.png",
    title: "Business Associate",
    rate: "$900 -1200/m",
    avai: "Full Time",
  },
  {
    index: 3,
    image: "../images/facebook.png",
    title: "Business Accociate",
    rate: "$900 -1200/m",
    avai: "Full Time",
  },
  {
    index: 4,
    image: "../images/linkdin.png",
    title: "Web Developer",
    rate: "$900 -1200/m",
    avai: "Full Time",
  },
];
